### PR TITLE
Setup Prettier for React code formatting

### PR DESCRIPTION
**Pull request by gatukgl**
Changes proposed in this pull request:

- Remove white space for project name in package.json due to I've got an error `Name contains illegal characters`
- Install prettier for code formatting
- Configure prettier
  - Don't allow adding `semi-colon` after the end of code line
  - Use single quote for javascript and jsx code
  - Add trailing comma
- Setup a hook to auto format the code before commit

### CODE REVIEW

**Comment by gatukgl** [comment]
@zkan เฮือกกก circleci พัง

**Comment by zkan** [comment]
@gatukgl We need to merge the PR that sets up the CircleCI first.

**Comment by zkan** [comment]
@gatukgl Rebase your PR and it should fix the CI ja.

**Comment by gatukgl** [comment]
@zkan รีวิวใหม่ๆๆๆ

**Pull request merged**
